### ISSUE TITLE
Pasting a string with ${xxxxx} does not work

### ISSUE THREAD

**Issue by gertst** [chamboug/vscode-extension-js-auto-backticks#12]
Example: Existing code:
`const a = "my string |";`
where the cursor is at |
Pasting in the string `${some text}` inside the above string does not convert the existing double quotes to backticks.

Very helpful extension nevertheless, so thanks a lot for sharing!

**Comment by chamboug** [comment]
Hi @gertst, thanks for opening this issue. I'll look into it.

**Comment by chamboug** [comment]
This has been fixed in `v1.0.0` I just released

**Comment by gertst** [comment]
Works as expected! Thanks for the fast update!
