### ISSUE TITLE
Make your extension available in VSCodium Marketplace?

### ISSUE THREAD

**Issue by OlivierMartineau** [chamboug/vscode-extension-js-auto-backticks#15]
Hey there!

Your (very handy) extension is open-source and tracker free: it would perfectly fit into [VSCodium Marketplace](https://open-vsx.org)!
As Chromium is the tracker free version of Chrome, VSCodium is the tracker-free version of VSCode, i.e. only the shared/open source code without addition.
The VSCodium Marketplace only shares extensions that are truly open-source AND tracker-free.

Wouldn't you want to share your precious extension there (and maybe adopt the tracker-free IDE ;) )?

**Comment by chamboug** [comment]
Hi @OlivierMartineau, thanks for opening this issue. I'll look into it.

**Comment by chamboug** [comment]
Hi @OlivierMartineau, the extension has been published to VSCodium Marketplace (available [here](https://open-vsx.org/extension/chamboug/js-auto-backticks)). Please let me know if everything works as expected.

**Comment by OlivierMartineau** [comment]
Thank you very much! It works perfectly, you made my day 🙏 
I wish you a pleasant end of week!
