### ISSUE TITLE
Revert to single quotes when no interpolations used

### ISSUE THREAD

**Issue by karlhorky** [chamboug/vscode-extension-js-auto-backticks#16]
Hi @chamboug, thanks for this extension 🙌 

I've been using [the VS Code extension Template String Converter](https://marketplace.visualstudio.com/items?itemName=meganrogge.template-string-converter) ([`meganrogge/template-string-converter`](https://github.com/meganrogge/template-string-converter)) by @meganrogge .

But this extension has some ideas that could also be features for your extension - one idea that you could look at is this feature:

> `template-string-converter.autoRemoveTemplateString`
>
> When `$` or `{` is deleted, replace backticks with quotes

This makes the transformation to a template string reversible as well, which can be helpful for a lot of situations.

What do you think?

**Comment by chamboug** [comment]
Hi @karlhorky, thanks for opening this issue. I'll look into it.

**Comment by karlhorky** [comment]
Great, thanks for that! Closing.
