### ISSUE TITLE
not working as intended 

### ISSUE THREAD

**Issue by LucasRTonin** [chamboug/vscode-extension-js-auto-backticks#17]
what could it be?
![Animation](https://github.com/chamboug/vscode-extension-js-auto-backticks/assets/30559272/59544981-ed15-4588-a030-3a02c882c4a4)

**Comment by chamboug** [comment]
Hi, since there hasn't been any activity on this issue for some time, I'll be closing it now. Feel free to reopen and provide more details if needed. Thank you.
