### ISSUE TITLE
Incorrectly changes quotes to backticks when typing in a backticked string

### ISSUE THREAD

**Issue by DanKaplanSES** [chamboug/vscode-extension-js-auto-backticks#7]
# Description
The extension incorrectly modifies quotes within backticks.

# Steps to reproduce
1. Create a JavaScript file
2. Place ``console.log(`foo: ''`);`` in it
3. Move your cursor between the `''`
4. Type `${`

# Expectation
The line becomes ``console.log(`foo: '${'`);``

# Actual
The line becomes ```console.log(`foo: `${}``);``` The extension changed the `'` into `` ` ``s. This is syntactically incorrect. Note: the same problem occurs if you swap `'` for `"` in the example.

# Workaround
You can edit the string after the fact or put the quotes in it after typing `${`.

**Comment by chamboug** [comment]
Hi @DanKaplanSES, thanks for opening this issue. I will have a look.
